CREATE DATABASE Marketing_Campaign;

USE Marketing_Campaign;

CREATE TABLE customers (
    ID INT PRIMARY KEY,
    Year_Birth INT,
    Education VARCHAR(50),
    Marital_Status VARCHAR(50),
    Income DECIMAL(10,2),
    Kidhome INT,
    Teenhome INT,
    Dt_Customer DATE,
    Recency INT,
    MntWines INT,
    MntFruits INT,
    MntMeatProducts INT,
    MntFishProducts INT,
    MntSweetProducts INT,
    MntGoldProds INT,
    NumDealsPurchases INT,
    NumWebPurchases INT,
    NumCatalogPurchases INT,
    NumStorePurchases INT,
    NumWebVisitsMonth INT,
    AcceptedCmp1 TINYINT,
    AcceptedCmp2 TINYINT,
    AcceptedCmp3 TINYINT,
    AcceptedCmp4 TINYINT,
    AcceptedCmp5 TINYINT,
    Response TINYINT,
    Complain TINYINT,
    Country VARCHAR(50),

    Age INT,
    Total_Spend DECIMAL(10,2),
    Total_Purchases INT,
    Children INT,
    Customer_Tenure INT,
    Web_Visitor_Type VARCHAR(50),
    High_Spender VARCHAR(50),
    Income_Segment VARCHAR(50),
    Young_Customer TINYINT,
    Campaign_Responder TINYINT,
    High_Web_Engagement TINYINT,
    Family_Customer TINYINT);